name: Pedro Matiello

title : Pedro Matiello
author :
  name : Pedro Matiello
  email: pedro@pmatiello.me
  twitter: pmatiello

production_url: http://www.pmatiello.me
permalink: /:year/:month/:title.html

collections:
  updates:
    output: true