markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Pedro Matiello
production_url : http://www.pmatiello.me
description: "Pedro Matiello's website."
#disqus_shortname: N/A
#analytics: N/A
author :
  name : Pedro Matiello
  github : pmatiello
  twitter : pmatiello
  email: pedro@pmatiello.me
