name: Pedro Matiello
markdown: redcarpet
pygments: true

title : Pedro Matiello
author :
  name : Pedro Matiello
  email: pedro@pmatiello.me

production_url: http://www.pmatiello.me
permalink: /:year/:month/:title.html
