name: Pedro Matiello
markdown: redcarpet
highlights: pygments

title : Pedro Matiello
author :
  name : Pedro Matiello
  email: pedro@pmatiello.me

production_url: http://www.pmatiello.me/
permalink: /:year/:month/:title.html
